version: '3.8'
services:
    db:
        image: mysql:latest
        volumes:
            - ./db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_NAME}'
    server:
        image: 'evotm/trackmania'
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            MASTER_PASSWORD: '${MASTER_PASSWORD}'
            SERVER_NAME: '${SERVER_NAME}'
            XMLRPC_ALLOWREMOTE: 'true'
            DISABLE_REPLAY_RECORDING: '${SYSTEM_DISABLE_REPLAYS}'
            SAVE_ALL_INDIVIDUAL_RUNS: '${SYSTEM_SAVE_RUNS}'
        healthcheck:
            test: 'nc -z -v 127.0.0.1 5000 || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        ports:
            - '${PORT}:2350/udp'
            - '${PORT}:2350/tcp'
        volumes:
            - 'serverData:/server/UserData'
    evosc:
        image: 'evotm/evosc'
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test: 'pgrep -x php || exit 1'
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s
        restart: always
        environment:
            MASTER_LOGIN: '${MASTER_LOGIN}'
            DB_HOST: '${DB_HOST}'
            DB_NAME: '${DB_NAME}'
            DB_USER: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
            RPC_IP: 'server'
            RPC_LOGIN: 'SuperAdmin'
            RPC_PASSWORD: 'SuperAdmin'
        volumes:
            - 'serverData:/server/UserData'
            - 'evoscConfig:/controller/config'
            - 'evoscModules:/controller/modules'
            - 'evoscCache:/controller/cache'
    musicserver:
        build: ../musicserver/
        ports:
              - "80:80"
        volumes:
            - ../musicserver/:/var/www/html
volumes:
    serverData: null
    evoscConfig: null
    evoscModules: null
    evoscCache: null
